const MOVIES_SERVER_URL = "https://api.nomoreparties.co";
// const SERVER_URL = "http://localhost:3001";
const SERVER_URL = "https://api.moviedallas.nomoredomainsrocks.ru"
const EMPTY_QUERY_ERROR = "Нужно ввести ключевое слово";
const SHORT_DURATION = 40;
const SEARCH_LOCAL_STORAGE_KEY = "searchFilms";
const MAX_MOBILE_SCREEN_DISPLAY = 630;
const TABLET_SCREEN_DISPLAY = 990;
const DESKTOP_SCREEN_DISPLAY = 1280;
const MIN_ADDING_STEP = 2;
const MIDDLE_ADDING_STEP = 3;
const MAX_ADDING_STEP = 4
const MOBILE_SCREEN_INITIAL_MOVIES_COUNT = 5;
const TABLET_SCREEN_INITIAL_MOVIES_COUNT = 8;
const DESKTOP_SCREEN_INITIAL_MOVIES_COUNT = 12;
const XL_DISPLAY_SCREEN_INITIAL_MOVIES_COUNT = 16;

export {
  MOVIES_SERVER_URL,
  SERVER_URL,
  EMPTY_QUERY_ERROR,
  SHORT_DURATION,
  SEARCH_LOCAL_STORAGE_KEY,
  MAX_MOBILE_SCREEN_DISPLAY,
  TABLET_SCREEN_DISPLAY,
  DESKTOP_SCREEN_DISPLAY,
  MIN_ADDING_STEP,
  MIDDLE_ADDING_STEP,
  MAX_ADDING_STEP,
  MOBILE_SCREEN_INITIAL_MOVIES_COUNT,
  TABLET_SCREEN_INITIAL_MOVIES_COUNT,
  DESKTOP_SCREEN_INITIAL_MOVIES_COUNT,
  XL_DISPLAY_SCREEN_INITIAL_MOVIES_COUNT
};
